name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: monolith

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: maartenRamadan
          runtime: java11
          project_id: micro-services
          entry_point: functions.micro-services

      - name: make the url authenticated
        run: |
          gcloud functions add-iam-policy-binding maartenRamadan --member="allUsers" --role="roles/cloudfunctions.invoker"
      # - name: test the url
      #   run: curl "${{ steps.deploy.outputs.url }}"

